version: "3"

services:
  mysql:
    container_name: mysql
    restart: always
    build:
      context: ./mysql/
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: sample_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - mysql_sock:/var/run/mysqld

volumes:
  mysql_volume:
  mysql_sock:
